load("@buildx//:defs.bzl", "buildx", "context")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load")

package(default_visibility = ["//visibility:public"])

buildx(
    name = "base_buildx_image",
    build_context = [
        context.oci_layout(
            "ubuntu:latest",
            "@ubuntu",
        ),
    ],
    dockerfile = ":Dockerfile-base",
)

oci_image(
    name = "base_oci_image",
    base = ":base_buildx_image",
)

oci_load(
    name = "base.load",
    image = ":base_oci_image",
    repo_tags = ["base:latest"],
)

buildx(
    name = "dev_buildx_image",
    build_context = [
        context.oci_layout(
            "base:latest",
            ":base_oci_image",
        ),
    ],
    dockerfile = ":Dockerfile-dev",
)

oci_image(
    name = "dev_oci_image",
    base = ":dev_buildx_image",
)

oci_load(
    name = "dev.load",
    image = ":dev_oci_image",
    repo_tags = ["dev:latest"],
)

genrule(
    name = "base_details",
    srcs = [
        ":base_oci_image",
    ],
    outs = [
        "base.label",
        "base.digest",
    ],
    cmd = """set -ex;
$(location :base.load) | awk -F: '/Loaded image:/ { print $$2 ":" $$3 }' > $(location :base.label);
docker images --quiet --no-trunc $$(cat $(location :base.label)) > $(location :base.digest);
""",
    tags = [
        "no-cache",
        "no-sandbox",
    ],
    target_compatible_with = [
        "@docker_config//:docker_yes",
    ],
    tools = [
        ":base.load",
    ],
)

genrule(
    name = "dev_details",
    srcs = [
        ":dev_oci_image",
    ],
    outs = [
        "dev.label",
        "dev.digest",
    ],
    cmd = """set -ex;
$(location :dev.load) | awk -F: '/Loaded image:/ { print $$2 ":" $$3 }' > $(location :dev.label);
docker images --quiet --no-trunc $$(cat $(location :dev.label)) > $(location :dev.digest);
""",
    tags = [
        "no-cache",
        "no-sandbox",
    ],
    target_compatible_with = [
        "@docker_config//:docker_yes",
    ],
    tools = [
        ":dev.load",
    ],
)
